import { initializeApp, getApps, getApp } from 'firebase/app';
import { 
  initializeFirestore, 
  persistentLocalCache, 
  persistentMultipleTabManager,
  getFirestore 
} from 'firebase/firestore';
import { 
  getAuth, 
  GoogleAuthProvider 
} from 'firebase/auth';

// ============================================================================
// FIREBASE CONFIGURATION KEYS
// ============================================================================
// If you are using this code outside AI Studio, paste your Firebase Config keys below:
/*
const myFirebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_PROJECT_ID.firebaseapp.com",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_PROJECT_ID.firebasestorage.app",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID"
};
*/

// Dynamically import config generated by AI Studio or fallback
import firebaseConfigJson from '../firebase-applet-config.json';

const firebaseConfig = {
  apiKey: firebaseConfigJson.apiKey || "YOUR_API_KEY",
  authDomain: firebaseConfigJson.authDomain || "YOUR_AUTH_DOMAIN",
  projectId: firebaseConfigJson.projectId || "YOUR_PROJECT_ID",
  storageBucket: firebaseConfigJson.storageBucket || "YOUR_STORAGE_BUCKET",
  messagingSenderId: firebaseConfigJson.messagingSenderId || "YOUR_SENDER_ID",
  appId: firebaseConfigJson.appId || "YOUR_APP_ID",
  measurementId: firebaseConfigJson.measurementId || undefined
};

// Initialize Firebase App
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();

// Initialize Firestore with Offline Persistence enabled (CRUCIAL REQUIREMENT)
let db;
try {
  db = initializeFirestore(app, {
    localCache: persistentLocalCache({
      tabManager: persistentMultipleTabManager()
    })
  });
} catch (err) {
  // Fallback if already initialized
  db = getFirestore(app);
}

// Initialize Auth & Providers
const auth = getAuth(app);
const googleProvider = new GoogleAuthProvider();
googleProvider.setCustomParameters({
  prompt: 'select_account'
});

export { app, db, auth, googleProvider, firebaseConfig };
